version: "3.5"

services:

  db:
    container_name: ${MYSQL_HOST}
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - teste-backend-wa-mysql-volume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db:${MYSQL_HOST}
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: galkaev

volumes:
  teste-backend-wa-mysql-volume: null
